ftnaija/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls'))
]

users/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views


app_name = 'users'
urlpatterns = [
   
    # path('signin/', views.googleSignin, name="login"),
    path('', views.register, name="register"),
    path('accounts/login/', views.login_attempt, name="signin"),
    path('accounts/profile/', views.profile, name="profile"),
    path('logout/',auth_views.LogoutView.as_view(), name='logout'),
    path('adminpage/', views.adminpage, name='adminpage'),
    path('userdash/<int:id>', views.userdash, name='userdash')
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db import models 
from datetime import datetime

class Profile(models.Model):
    
    def __str__(self):
        return str(self.userid)
    
    userid = models.ForeignKey(User, default=1, on_delete = models.CASCADE)
    amount = models.IntegerField(default=100)
   
    

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth import get_user_model
from .models import Profile

user_model = get_user_model()

class NewUserForm(UserCreationForm):
    password1 = forms.CharField(label='Enter password', widget=forms.PasswordInput)
    
    class Meta:
        model = user_model
        fields = [
            'username',
            'password1',
            'password2',
        ]
        help_texts = {
            'username': None,
            'password2': None,
        }
        
    def save(self,commit=True):
        user = super(NewUserForm,self).save(commit=False)
        if commit:
            user.save()
        return user
    

users/views.py
from django.shortcuts import render,redirect
from .models import Profile
from django.contrib.auth import authenticate,login
from .forms import NewUserForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import get_user_model



def login_attempt(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user_obj = User.objects.filter(username = username).first()
        if user_obj is None:
            messages.error(request, "we can't find this account! kindly signup.")
            return redirect('users:signin')

        user = authenticate(username = username, password = password)
        print(user)
        if user is None:
            messages.error(request, 'Wrong password.')
            return redirect('users:signin')
        
        login(request , user)
        
        #if profile_obj.is_completed == False:
 
        return redirect('users:profile')

    return render(request , 'login.html')

def register(request):
    form = NewUserForm()
    
    # usernames = []
    # allusers = User.objects.all()
    # usern = allusers.values('username')
    # for keys in usern:
    #     usernames.append(keys['username'])
    
    if request.method =='POST':
        form = NewUserForm(request.POST)
        
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            
            user_obj = User(username = username , password=password)
            user_obj.set_password(password)
            #user_obj.save()
            
            profile_obj = Profile.objects.create(userid = user , amount=100)
            profile_obj.save()
            
            return redirect('/accounts/login')
        else:
            messages.error(request, 'account not created for some reasons')
        
    context={
        'form':form,
    }
    return render(request,'register.html',context)
    

@login_required
def profile(request):
    current_user = User.objects.get(id=request.user.id)
    profile_obj = Profile.objects.filter(userid =current_user)

    amountlist = []
    timelist = [0]
    
    
    print(amountlist)
    print(timelist)
    
    for data in profile_obj.all():
        amountlist.append(data.amount)
        
        
    for i in range(len(amountlist) -1):
        timelist.append((i+1)*60)
    
    if request.method == 'POST':
        amount = request.POST['amount']
        # time = request.POST['time']

        newdata = Profile.objects.create(userid = current_user, amount=amount)
        newdata.save()
        
    context = {
        'profile_obj' : profile_obj,
        'amountlist' : amountlist,
        'timelist': timelist,
        'data' : current_user
    }
    
    return render(request, 'profile.html', context)


def adminpage(request):
    allusers = get_user_model().objects.all()
    
    theusers = allusers[1:]
  
    if request.method == 'POST':
        name = request.POST['username']
        print(name)
    
    context = {
        'allusers' : theusers,
    }
    
    return render(request, 'adminpage.html', context)

def userdash(request, id):
    clickeduser = User.objects.get(id = id)
  
    profile_obj = Profile.objects.filter(userid =clickeduser)

    amountlist = []
    timelist = []
    
    for data in profile_obj.all():
        amountlist.append(data.amount)
        
    for i in range(len(amountlist)):
        timelist.append((i+1)*60)
        
    print(amountlist)
    print(timelist)
    
    context = {
        'clickeduser' : clickeduser,
        'amountlist' : amountlist,
        'timelist' : timelist
    }
    
    return render(request, 'userdash.html', context)
    

users/templates/adminpage.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

   
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.0.2/dist/chart.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>FT9ja</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg" style="background-color: rgb(22, 58, 175);">
        <div class="container-fluid">
          <a class="navbar-brand" href="#" style="font-weight: bold;">FT9ja Admin</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        
        </div>
    </nav>

    <div class="admin">

        <div class="container">
            <div class="users">
                    {% for user in allusers %}
                    <a href="{% url 'users:userdash' user.id %}" id="button" onclick="clickedButton()">{{user}}</a>
                    {% endfor %}
            </div>
        </div>
    </div>

<script src="{% static 'js/script.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

  </body>
</html>

users/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.0.2/dist/chart.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>FT9ja</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">FT9ja</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav" style="margin-left: 90%;">
                <!-- <a class="nav-link active" aria-current="page" href="#">Home</a> -->
              {% if user.is_authenticated %}
              <a class="nav-link ative" href="{% url 'users:logout' %}">Logout</a>
              {% else %}
              <a class="nav-link active" href="{% url 'users:signin' %}" >Login</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
   

    <div class="container">

        {% block content %}

        {% endblock %}

    </div>


<script src="{% static 'js/script.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

  </body>
</html>

users/templates/login.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}

{% include 'messages.html' %}

        <div class="main row">
            <div class="col-lg-6 col-sm-12">
                <div class="form-group mx-auto" style="max-height: 600px;">
               
                    <form action="" method="post" class=" mb-0" style="max-height: 500px;">
                        {% csrf_token %}
                        <div class="mb-2">
                            <label>Username</label>
                            <input type="text" name="username" class="form-control form-control-md" id="exampleInputEmail1" aria-describedby="emailHelp">
                        </div>
            
                        <div class="pb-3 pt-4">
                            <div class="d-flex" style="justify-content: space-between;">
                                <label>Password</label>
                                <label><a href="" 
                                style="font-size: 12px; padding-bottom:0; margin-top: 30px; color: rgb(21, 71, 235);;">Forgot password?</a></label>
                            </div>
                            <input type="password" name="password" class="form-control form-control-md" id="exampleInputPassword1">
                        </div>
            
                        <button type="submit" class="btn">Sign in</button>
            
            
                    {% comment %} Already Registered {% endcomment %}
                    <div class="w-30 pt-4">
                        <p class="text-muted" style="text-align: center;">
                            Don't have an account?
                            <a href="{% url 'users:register' %}">Create account</a>
                        </p>
                    </div>
                </form>
                </div>
            </div> 
        </div>

    {% endblock %}

  

users/templates/messages.html
{% if messages %}
    {% for message in messages %}
    <div class="container-fluid p-0" id="error_message">
    <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true"onclick="closeError()" class="p-0" style="border: none;">×</span>
        </button>
        {{ message }}
    </div>
    </div>
    {% endfor %}
{% endif %}

<script>
    function closeError(){
        document.getElementById('error_message').style.display='none'
    }
</script>

users/templates/profile.html
{% extends 'base.html' %}

{% block content %}

<div>
    <h3 class="text-center">{{data.username}}'s Dashboard</h3>
</div>

   <h2 id="refresh-timer" style="display: none;">0</h2>

   <h5 class="text-center">Initial Amount: $<span id="amount">100</span></h5>

   <h4 id="result">GAIN/LOSS</h2>

   <!-- <h3>{{amountlist}}</h3>

   <h4>{{timelist}}</h4> -->

   <form action="" method="post">
    {% csrf_token %}
    <input type="text" name="amount" value="" id="inputamount" hidden>
    <input type="text" name="time" value="" id="inputtime" hidden>
    <input type="submit" value="" id="submit" hidden>
   </form>

   <div class="col-md-12">
    <canvas id="myChart" width="400" height="200"></canvas>
        <script>
        var ctx = document.getElementById('myChart').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: [{% for time in timelist %}  '{{ time }}secs',  {% endfor %}],
                
                datasets: [{
                    label: 'Amount',
                    data: [{% for amounts in amountlist %}  {{ amounts }},  {% endfor %}],
                    
                    borderColor: [
                        'rgba(75, 192, 192, 1)',
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        //'rgba(153, 102, 255, 1)',
                        //'rgba(255, 159, 64, 1)',
                        //'rgba(240, 120, 50, 1)',
                    ],
                    
                    borderWidth: 2
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
        </script>
</div>

   <script>
    
   </script>


   {% endblock %}

users/templates/register.html
{% extends 'base.html' %}
{% block content %}

{% load crispy_forms_tags %}

{% include 'messages.html' %}

<div class="main row">
    <div class="col-lg-6 col-sm-12">
        <div class="form-group mx-auto" style="max-height: 600px;">
       
            <form action="" method="post" class=" mb-0" style="max-height: 600px;">
                        {% csrf_token %}
                        <div class="mb-2">
                            <label>Username</label>
                            <input type="text" name="username" class="form-control form-control-md" id="exampleInputEmail1" aria-describedby="emailHelp">
                        </div>
            
                        <div class="pb-3 pt-4">
                            
                                <label>Password</label>
                                <input type="password" name="password1" class="form-control form-control-md" id="exampleInputPassword1">
                        </div>

                        <div class="pb-3 pt-4">
                                <label>confirm Password</label>
                                <input type="password" name="password2" class="form-control form-control-md" id="exampleInputPassword1">
                        </div>
                
                        <div class="row d-flex mx-auto" style="width:100%">
                            <button type="submit" class="btn w-50" >Register</button>
                            <p class="my-3 col-lg-6 col-sm-12">
                                Already Registered?
                                <a href="{% url 'users:signin' %}"> Login </a>
                            </p>
                        </div>
                    </form>
                </div>
            </div>
            </div>

    {% endblock %}

users/templates/userdash.html
{% extends 'base.html' %}

{% block content %}

<div>
    <h3 class="text-center">{{clickeduser}}'s Dashboard</h3>
</div>

   <h2 id="refresh-timer" style="display: none;">0</h2>

   <h5 class="text-center">Initial Amount: $<span id="amount">100</span></h5>

   <h4 id="result"></h2>

   <!-- <h3>{{amountlist}}</h3>

   <h4>{{timelist}}</h4> -->

   <!-- <form action="" method="post">
    {% csrf_token %}
    <input type="text" name="amount" value="" id="inputamount" hidden>
    <input type="text" name="time" value="" id="inputtime" hidden>
    <input type="submit" value="" id="submit" hidden>
   </form> -->

   <div class="col-md-12">
    <canvas id="myChart" width="400" height="200"></canvas>
        <script>
        var ctx = document.getElementById('myChart').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: [{% for time in timelist %}  '{{ time }}secs',  {% endfor %}],
                
                datasets: [{
                    label: 'Amount',
                    data: [{% for amounts in amountlist %}  {{ amounts }},  {% endfor %}],
                    
                    borderColor: [
                        'rgba(75, 192, 192, 1)',
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        //'rgba(153, 102, 255, 1)',
                        //'rgba(255, 159, 64, 1)',
                        //'rgba(240, 120, 50, 1)',
                    ],
                    
                    borderWidth: 2
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
        </script>
</div>

   <script>
    
   </script>


   {% endblock %}